import type { Metadata } from 'next'
import './globals.css'
import Link from 'next/link'
import HamburguerMenu from '@/components/HamburguerComponent'

export const metadata: Metadata = {
  title: 'Piadas sobre a lenda de Chuck Norris',
  description: 'Generated by create next app',
}

export default function RootLayout({children,}: {
  children: React.ReactNode
}) {
  const linkStyles = `hover:text-red-400 text-sm md:text-2xl`
  const bodyStyles = `flex flex-col md:flex-row items-center justify-center min-h-screen  bg-gray-800`
  return (
    <html lang="pt-BR">
      <body className={bodyStyles}>
            <div className='w-fit sm:block md:hidden absolute top-0 left-0 bg-orange-300 px-1 m-1 rounded-md'>
              <HamburguerMenu />
            </div>
          <header className='hidden z-10 border-2 border-sky-500 rounded-l-lg sm:flex w-72 px-2 h-screen flex-col bg-yellow-200'>
            <nav className='flex flex-col gap-y-10 w-full my-auto text-zinc-800 text-xl'>
              <Link className= {linkStyles} href="/">Home page</Link>
              <Link className= {linkStyles} href="/jokes">Fatos</Link>
              <Link className= {linkStyles} href="/jokescategory">Fatos por categoria</Link>
            </nav>
          </header>
        <main className='flex flex-grow items-center justify-center'>
        {children}
        </main>
        </body>
    </html>
  )
}
